# Generated from CoinLogic source traces; rules remain keyed by source_id.
SOURCE_LAYOUTS = {
    'Bob-omb Battlefield': (
        ('start_breakable_coin_box', 'Large breakable coin box near the start', 'yellow', 3),
        ('start_throwable_cork_boxes', 'Two throwable cork boxes near the start', 'yellow', 6),
        ('main_horizontal_coin_lines', 'Three horizontal coin lines', 'yellow', 15),
        ('main_wooden_posts', 'Five wooden posts', 'yellow', 25),
        ('flowerbed_coin_ring', 'Flowerbed Coin Ring', 'yellow', 8),
        ('main_bob_ombs', 'Twelve Bob-ombs', 'yellow', 12),
        ('main_goombas', 'Eleven Goombas', 'yellow', 11),
        ('main_koopa_troopa', 'Koopa Troopa', 'blue', 1),
    ),
    "Whomp's Fortress": (
        ('start_throwable_cork_boxes', 'Two throwable cork boxes', 'yellow', 6),
        ('start_flower_coin_ring', 'Flower Patch Coin Ring', 'yellow', 8),
        ('start_coin_line', 'Coin line near the beginning', 'yellow', 5),
        ('falling_bridge_coin_line', 'Coin line past the falling bridge', 'yellow', 5),
        ('rotating_plank_coins', 'Coins around the rotating plank', 'yellow', 4),
        ('water_slope_coin_line', 'Coin line on the slope from the water', 'yellow', 5),
        ('water_coin_ring', 'Water Coin Ring', 'yellow', 8),
        ('buddy_coin_line', 'Coin line near the Bob-omb Buddy', 'yellow', 5),
        ('whomp_jump_coins', 'Coins from jumping on two Whomps', 'yellow', 10),
        ('piranha_plant_coins', 'Three Piranha Plants', 'blue', 3),
        ('wild_blue_coin_ring', 'Shoot into the Wild Blue Coin Ring', 'yellow', 8),
        ('whomp_ground_pound_coins', 'Ground Pound bonus from two Whomps', 'yellow', 10),
        ('blue_coin_block', 'Blue Coin Block', 'blue', 4),
        ('top_floating_isle_ring', 'Coin ring on the floating isle', 'yellow', 8),
        ('top_floating_arrow', 'Coin arrow above the fortress', 'yellow', 8),
    ),
    'Jolly Roger Bay': (
        ('start_three_coin_block', '3-Coin Block near the start', 'yellow', 3),
        ('clam_vertical_coin_ring', 'Vertical coin ring near the clams', 'yellow', 8),
        ('tall_spike_coin_ring', 'Coin ring around the tall spike', 'yellow', 8),
        ('purple_switch_lower_coin_line', 'Lower part of the Purple Switch coin line', 'yellow', 3),
        ('jet_stream_coin_ring', 'Coin ring near the jet stream', 'yellow', 8),
        ('cave_chest_coin_ring', 'Coin ring near the cave treasure chests', 'yellow', 8),
        ('main_goombas', 'Three Goombas', 'yellow', 3),
        ('purple_switch_upper_coin_line', 'Upper part of the Purple Switch coin line', 'yellow', 2),
        ('raised_ship_approach_coin_lines', 'Coin lines leading to the raised ship', 'yellow', 15),
        ('blue_coin_block', 'Blue Coin Block', 'blue', 6),
    ),
    'Cool, Cool Mountain': (
        ('penguin_slide_yellow_coins', 'Individual coins on the Penguin Slide', 'yellow', 27),
        ('penguin_slide_coin_lines', 'Nine coin lines on the Penguin Slide', 'yellow', 45),
        ('chimney_vertical_coin_line', 'Vertical coin line into the chimney', 'yellow', 5),
        ('main_mountain_coin_lines', 'Four Snowman Slide coin lines', 'yellow', 20),
        ('standard_mr_blizzard', 'Mr. Blizzard', 'yellow', 3),
        ('main_spindrifts', 'Three Spindrifts on the main route', 'yellow', 9),
        ('slide_blue_coin', 'Blue Coin at the start of the slide', 'blue', 1),
        ('wall_kicks_coin_arrow', 'Coin arrow near Wall Kicks Will Work', 'yellow', 8),
        ('wall_kicks_spindrifts', 'Two Spindrifts near Wall Kicks Will Work', 'yellow', 6),
        ('blue_coin_block', 'Blue Coin Block', 'blue', 2),
    ),
    "Big Boo's Haunt": (
        ('mansion_ten_coin_block', '10-Coin Block behind the mansion', 'yellow', 10),
        ('shed_breakable_coin_boxes', 'Two breakable coin boxes near the shed', 'yellow', 6),
        ('outside_crazy_box', 'Crazy Box outside the mansion', 'yellow', 5),
        ('outside_scuttlebugs', 'Three Scuttlebugs outside', 'yellow', 9),
        ('main_boos', 'Five Boos in the mansion', 'blue', 5),
        ('main_mr_is', 'Two Mr. Is', 'blue', 2),
        ('main_bookend', 'Flying Bookend on the first floor', 'blue', 1),
        ('second_floor_bookends', 'Two Flying Bookends on the second floor', 'blue', 2),
        ('second_floor_mr_i', 'Mr. I on the second floor', 'blue', 1),
        ('third_floor_boo', 'Boo behind the third-floor Vanish Cap barrier', 'blue', 1),
        ('attic_blue_coin_block', 'Blue Coin Block in the attic', 'blue', 4),
        ('merry_go_round_boos', 'Five Merry-Go-Round Boos', 'blue', 5),
    ),
    'Hazy Maze Cave': (
        ('start_coin_line', 'Rolling Rocks Coin Line', 'yellow', 5),
        ('maze_entrance_coin_line', 'Coin line before the maze', 'yellow', 5),
        ('rolling_rocks_coins', 'First Room Coins', 'yellow', 5),
        ('lake_approach_coin_ring', 'Swimming Beast in the Cavern Star Coin Ring', 'yellow', 8),
        ('first_room_scuttlebugs', 'Two Scuttlebugs in the first room', 'yellow', 6),
        ('pit_room_scuttlebug', 'Scuttlebug in the pit room', 'yellow', 3),
        ('amazing_emergency_exit_swoop_1', 'A-Maze-Ing Emergency Exit Swoop 1', 'yellow', 1),
        ('red_coin_room_scuttlebugs', 'Two Scuttlebugs in the Red Coin room', 'yellow', 6),
        ('toxic_maze_snufits', 'Four Snufits in the toxic maze', 'yellow', 8),
        ('toxic_maze_swoops', 'Four Swoops in the toxic maze', 'yellow', 4),
        ('red_coin_room_mr_is', 'Two Mr. Is in the Red Coin room', 'blue', 2),
        ('pit_island_room_swoop', 'Pit Island Room Swoop', 'yellow', 1),
        ('amazing_emergency_exit_swoop_2', 'A-Maze-Ing Emergency Exit Swoop 2', 'yellow', 1),
        ('upper_red_coin_swoops', 'Two Checkerboard Platform Ride Swoops', 'yellow', 2),
        ('pit_islands_ceiling_coin_line', 'Coin line leading to the toxic maze star', 'yellow', 5),
        ('swimming_beast_coin_ring', 'Past Rolling Rocks 1-Up Block Coin Ring', 'yellow', 8),
        ('toxic_maze_star_coin_line', 'Coin line on the hangable ceiling above Pit Islands', 'yellow', 5),
        ('toxic_maze_exit_swoops', 'Two additional Swoops on the toxic maze route', 'yellow', 2),
        ('metal_head_scuttlebug', 'Scuttlebug on the Metal-Head Mario Can Move route', 'yellow', 3),
        ('toxic_maze_blue_coin_block', 'Blue Coin Block in the toxic maze', 'blue', 7),
    ),
    'Lethal Lava Land': (
        ('lll_tilting_platform_coin_line', 'Coin Line under the Bridge', 'yellow', 5),
        ('lll_grey_ramp_coins', 'First Grey Crescent Coins', 'yellow', 3),
        ('lll_bowser_puzzle_coins', 'Bowser Puzzle reward', 'yellow', 5),
        ('lll_first_big_bully_coin_line', 'First Sinking Platform Coin Line', 'yellow', 5),
        ('lll_second_big_bully_coin_ring', 'Beige Platform Coin Ring', 'yellow', 8),
        ('lll_northwest_ramp_coin_line', 'Coin Line on the Sinking Platform near the Big Bully', 'yellow', 5),
        ('lll_sinking_platform_coins', 'Coins on the sinking platforms near the Crazy Box', 'yellow', 4),
        ('lll_north_volcano_coin_line', 'Sinking Platform near the Volcano Coin Line', 'yellow', 5),
        ('lll_two_bullies_coin_ring', 'Bully the Bullies Coin Ring', 'yellow', 8),
        ('lll_spinning_volcano_platform_coins', 'Coins on the spinning platform around the volcano', 'yellow', 3),
        ('lll_southeast_grey_ramp_coins', 'Central Gray Crescent Coins', 'yellow', 4),
        ('lll_second_mr_i_coin_ring', 'Mr. I Island Coin Ring', 'yellow', 8),
        ('lll_crazy_box_coins', 'Crazy Box', 'yellow', 5),
        ('lll_outside_bullies', 'Eight Bullies outside the volcano', 'yellow', 8),
        ('lll_mr_is', 'Two Mr. Is', 'blue', 2),
        ('lll_under_bridge_coin_line', 'Northeast Brown Platform Coin Line', 'yellow', 5),
        ('lll_volcano_s_island_coins', 'Volcano S-shaped island coins', 'yellow', 3),
        ('lll_volcano_first_ridge_coin_line', 'Volcano first ridge coin line', 'yellow', 5),
        ('lll_volcano_second_ridge_coins', 'Volcano second ridge coins', 'yellow', 2),
        ('lll_volcano_floating_platform_coins', 'Volcano floating platform coins', 'yellow', 4),
        ('lll_volcano_post_platform_coin', 'Volcano coin after the floating platforms', 'yellow', 1),
        ('lll_volcano_second_bully_coin_line', 'Volcano second Bully coin line', 'yellow', 5),
        ('lll_volcano_checkerboard_lift_coin', 'Volcano coin by the checkerboard lift', 'yellow', 1),
        ('lll_volcano_bullies', 'Bullies inside the volcano', 'yellow', 2),
        ('lll_elevator_tour_platform_coins', 'Tiny platforms by Elevator Tour in the Volcano', 'yellow', 3),
    ),
    'Shifting Sand Land': (
        ('ssl_throwable_cork_box', 'Throwable cork box under the stone structure', 'yellow', 3),
        ('ssl_pillar_and_pyramid_coins', 'Coins on the pillars and inside the pyramid', 'yellow', 6),
        ('ssl_behind_pyramid_coin_line', 'Line of coins between the two pillars behind the pyramid', 'yellow', 5),
        ('ssl_pyramid_side_coin_line', 'Line of coins on the pyramid', 'yellow', 5),
        ('ssl_fly_guys', 'Fly Guys', 'yellow', 6),
        ('ssl_crazy_boxes', 'Crazy Boxes', 'yellow', 10),
        ('ssl_bob_ombs', 'Bob-ombs', 'yellow', 2),
        ('ssl_pokeys', 'Pokeys', 'blue', 4),
        ('ssl_goombas', 'Goombas inside and outside the pyramid', 'yellow', 12),
        ('ssl_first_wire_grid_coin_ring', 'Pyramid Coin Ring under the First Wire Grid', 'yellow', 8),
        ('ssl_second_wire_grid_coin_line', 'Pyramid Coin Line under the Second Wire Grid', 'yellow', 5),
        ('ssl_pyramid_top_horizontal_coin_line', 'Horizontal coin line at the top of the pyramid', 'yellow', 5),
        ('ssl_pyramid_top_vertical_coin_line', 'Vertical coin line at the top of the pyramid', 'yellow', 5),
        ('ssl_upper_pyramid_single_coins', 'Moving-step and Pyramid Puzzle secret coins', 'yellow', 13),
        ('ssl_blue_coin_block', 'Blue Coin Block', 'blue', 3),
    ),
    'Dire, Dire Docks': (
        ('ddd_start_wall_coin_line', 'Sloped underwater coin line near the start', 'yellow', 5),
        ('ddd_chest_and_current_coin_lines', 'Vertical Coin Lines by the Whirlpool and Chest', 'yellow', 10),
        ('ddd_seafloor_chest_coins', 'Coins surrounding the sea-floor chest', 'yellow', 3),
        ('ddd_sub_area_coin_rings', 'Coin Rings Leading to and Inside the Tunnel', 'yellow', 24),
        ('ddd_seafloor_clam_coin_ring', 'Sea-floor coin ring by the Koopa Shell clam', 'yellow', 8),
        ('ddd_moat_exit_coin_line', 'Vertical coin line by the moat exit', 'yellow', 5),
        ('ddd_sub_area_dock_coin_line', "Coin line on the Bowser's Sub area dock", 'yellow', 5),
        ('ddd_blue_coin_block', 'Blue Coin Block', 'blue', 6),
    ),
    "Snowman's Land": (
        ('sl_start_coins', 'Coins to the left of the start', 'yellow', 2),
        ('sl_spindrifts', 'Eight outdoor Spindrifts', 'yellow', 24),
        ('sl_start_mr_blizzards', 'Three Mr. Blizzards', 'yellow', 9),
        ('sl_moneybags', 'Two Moneybags', 'yellow', 10),
        ('sl_fly_guy', 'Fly Guy', 'yellow', 2),
        ('sl_whirl_mr_blizzard', 'Mr. Blizzard in the Whirl from the Freezing Pond area', 'yellow', 3),
        ('sl_upper_slope_coin_line', 'Coin line on the slope toward the Igloo', 'yellow', 5),
        ('sl_upper_slope_single_coins', 'Single coins on the slope toward the Igloo', 'yellow', 3),
        ('sl_penguin_and_face_coins', "Coins leading to Snowman's Big Head", 'yellow', 3),
        ('sl_upper_spindrifts', 'Three additional outdoor Spindrifts', 'yellow', 9),
        ('sl_igloo_goombas', 'Three Goombas inside the Igloo', 'yellow', 3),
        ('sl_snowman_head_plank_coins', 'Coins on the wooden plank near the top of the snowman', 'yellow', 2),
        ('sl_igloo_frozen_coin_lines', 'Frozen coin lines inside the Igloo', 'yellow', 20),
        ('sl_igloo_single_coins', 'Single coins inside the Igloo', 'yellow', 3),
        ('sl_igloo_three_coin_block', '3-Coin Block inside the Igloo', 'yellow', 3),
        ('sl_igloo_spindrifts', 'Three Spindrifts inside the Igloo', 'yellow', 9),
        ('sl_impossible_coin', 'Impossible Coin trick', 'yellow', 1),
    ),
    'Wet-Dry World': (
        ('main_skeeters', 'Two Skeeters in the main area', 'yellow', 6),
        ('amp_ring', 'Coin ring around the Amp pillar', 'yellow', 8),
        ('pillar_ten_coin_block', 'Pedestal 10-Coin Block', 'yellow', 10),
        ('push_block_three_coin_block', 'Push Block 3-Coin Block', 'yellow', 3),
        ('low_breakable_boxes', 'Breakable coin boxes at low water', 'yellow', 12),
        ('low_ten_coin_block', 'Push Block 10-Coin Block', 'yellow', 10),
        ('low_blue_coins', 'Blue coins at low water', 'blue', 6),
        ('wooden_structure_three_coin_block', 'Wooden Structure 3-Coin Block', 'yellow', 3),
        ('fourth_diamond_coin_line', 'Coin line by the fourth water-level diamond', 'yellow', 5),
        ('top_coin_line', 'Coin line at the highest water-level diamond', 'yellow', 5),
        ('top_chuckya', 'Chuckya at the top', 'yellow', 5),
        ('express_elevator_ten_coin_block', 'Top of Express Elevator 10-Coin Block', 'yellow', 10),
        ('downtown_ring', 'Downtown statue coin ring', 'yellow', 8),
        ('downtown_metal_cap_line', 'Downtown Narrow Plank Coin Line', 'yellow', 5),
        ('downtown_first_building_line', 'Beige Building Coin Line', 'yellow', 5),
        ('downtown_second_building_line', 'Gray Building Coin Line', 'yellow', 5),
        ('downtown_skeeters', 'Two Skeeters Downtown', 'yellow', 6),
    ),
    'Tall, Tall Mountain': (
        ('ttm_start_coin_ring', 'Coin ring at the start', 'yellow', 8),
        ('ttm_crazy_box', 'Crazy Box', 'yellow', 5),
        ('ttm_start_goombas', 'Three Goombas in the starting area', 'yellow', 3),
        ('ttm_middle_bob_ombs', 'Three Bob-ombs in the Middle area', 'yellow', 3),
        ('ttm_middle_chuckya', 'Chuckya in the Middle area', 'yellow', 5),
        ('ttm_middle_bridge_coin_line', 'Coin line on the bridge from Chuckya to the Bob-omb Buddy', 'yellow', 5),
        ('ttm_middle_fly_guy', 'Fly Guy in the Middle area', 'yellow', 2),
        ('ttm_upper_goombas', 'Three Goombas in the Upper area', 'yellow', 3),
        ('ttm_upper_bob_ombs', 'Two Bob-ombs in the Upper area', 'yellow', 2),
        ('ttm_upper_leaf_coin_line', 'Upper Vine Wall Hangable Ceiling Coin Line', 'yellow', 5),
        ('ttm_top_goombas', 'Three Goombas in the Top area', 'yellow', 3),
        ('ttm_hidden_coin_before_slide', 'Hidden single yellow coin before the slide', 'yellow', 1),
        ('ttm_slide_single_coins', 'Single yellow coins on the slide', 'yellow', 26),
        ('ttm_slide_coin_lines', 'Four coin lines on the slide', 'yellow', 20),
        ('ttm_slide_blue_coins', 'Single blue coins on the slide', 'blue', 3),
        ('ttm_slide_entrance_coin_line', 'Coin line by the slide entrance', 'yellow', 5),
        ('ttm_top_switch_base_coins', 'Lower coins by the Purple Switch near the mountain top', 'yellow', 2),
        ('ttm_waterfall_bridge_coin_line', 'Coin line on the rock bridge beside the waterfall', 'yellow', 5),
        ('ttm_top_switch_middle_coins', 'Middle coins by the Purple Switch near the mountain top', 'yellow', 2),
        ('ttm_top_switch_highest_coin', 'Highest coin by the Purple Switch near the mountain top', 'yellow', 1),
    ),
    'Tiny-Huge Island': (
        ('tiny_start_goomba', 'Small Goomba in the starting Tiny region', 'yellow', 1),
        ('tiny_piranha_area_plant', 'Tiny Island Fire Piranha Plant', 'yellow', 1),
        ('tiny_main_individual_coins', 'Tiny Island Coins', 'yellow', 9),
        ('tiny_main_coin_line', 'Coin line on the Tiny Island wooden plank', 'yellow', 5),
        ('tiny_main_three_coin_block', '3-Coin Block on Tiny Island', 'yellow', 3),
        ('tiny_main_goombas', 'Nine Tiny Island Goombas', 'yellow', 9),
        ('tiny_main_koopa', 'Tiny Island Koopa Troopa', 'blue', 1),
        ('tiny_purple_switch_coin', 'Five Itty Bitty Secrets Island Coin', 'yellow', 1),
        ('huge_start_giant_goombas', 'Three Huge Starting Area Giant Goombas', 'giant', 3),
        ('near_cannon_giant_goomba', 'Near Cannon Giant Goomba', 'giant', 1),
        ('huge_start_post', 'Wooden post at Huge Island start', 'yellow', 5),
        ('huge_beach_coins', 'Huge Island Beach Coins', 'yellow', 2),
        ('huge_beach_fly_guy', 'Beach Fly Guy', 'yellow', 2),
        ('huge_near_cannon_fly_guy', 'Near Cannon Fly Guy', 'yellow', 2),
        ('huge_lakitu', 'Lakitu on Huge Island', 'yellow', 5),
        ('huge_koopa_troopa', 'Koopa Troopa on Huge Island', 'blue', 1),
        ('huge_lakitu_island_post', "Wooden post on Lakitu's island", 'yellow', 5),
        ('huge_windswept_line', 'Coin line in Windswept Valley', 'yellow', 5),
        ('huge_windswept_giant_goombas', 'Two Giant Goombas in Windswept Valley', 'giant', 2),
        ('huge_cannonball_line', 'Coin line in the Cannonball area', 'yellow', 5),
        ('huge_cannonball_fly_guy', 'Fly Guy in the Cannonball area', 'yellow', 2),
        ('huge_koopa_region_line', "Coin line in Koopa the Quick's area", 'yellow', 4),
        ('tiny_impossible_coin', 'Impossible Coin', 'yellow', 1),
        ('huge_koopa_region_giant_goombas', "Three Giant Goombas in Koopa the Quick's area", 'giant', 3),
        ('huge_top_wooden_plank_line', 'Coin line on the Huge Island top plank', 'yellow', 5),
        ('huge_top_chuckya', 'Chuckya', 'yellow', 5),
        ('red_area_giant_goombas', 'Two Giant Goombas in the Red Coins Area', 'giant', 2),
        ('red_area_blue_coins', 'Blue coins in the Red Coins Area', 'blue', 2),
        ('red_area_plank_line', 'Coin line on the Red Coins Area plank', 'yellow', 5),
        ('wiggler_cave_coin_lines', "Coin lines in Wiggler's Cave", 'yellow', 10),
        ('huge_piranha_area_plants', 'Fire Piranha Plants in the Huge Piranha Area', 'yellow', 10),
    ),
    'Tick Tock Clock': (
        ('ttc_start_ten_coin_block', '10-Coin Block behind the start', 'yellow', 10),
        ('ttc_start_bob_ombs', 'Two Bob-ombs', 'yellow', 2),
        ('ttc_start_cube_coins', 'Coins above the first turning cube', 'yellow', 2),
        ('ttc_second_pendulum_block', '3-Coin Block behind the second pendulum', 'yellow', 3),
        ('ttc_first_hand_block', '3-Coin Block by the first moving hand', 'yellow', 3),
        ('ttc_first_pole_coin_line', 'Slanted coin line by the first pole (moving time, or stopped-time movement)', 'yellow', 5),
        ('ttc_heave_ho_blocks', 'Two 3-Coin Blocks by the Heave-Hos', 'yellow', 6),
        ('ttc_blue_coin_block', 'Blue Coin Block by The Pit and the Pendulums', 'blue', 7),
        ('ttc_past_three_spinners_block', 'Past Three Spinners 3-Coin Block', 'yellow', 3),
        ('ttc_top_central_platform_block', 'Top Central Platform 10-Coin Block', 'yellow', 10),
        ('ttc_timed_jumps_block', 'Above Timed Jumps on Moving Bars 3-Coin Block', 'yellow', 3),
        ('ttc_beneath_thwomp_block', '10-Coin Block beneath the Thwomp', 'yellow', 10),
        ('ttc_four_moving_bars_block', 'Above Four Moving Bars 10-Coin Block', 'yellow', 10),
        ('ttc_top_clock_hand_block', 'Top Clock Hand 10-Coin Block', 'yellow', 10),
    ),
    'Rainbow Ride': (
        ('rr_first_platform_ring', 'Coin ring at the first carpet platform', 'yellow', 8),
        ('rr_fly_guy_line', 'Coin line by the Fly Guy', 'yellow', 5),
        ('rr_fly_guy', 'Fly Guy', 'yellow', 2),
        ('rr_first_swing_line', 'First Swing Vertical Coin Line', 'yellow', 5),
        ('rr_first_donut_lift_coins', 'Coins on the first Donut Lifts', 'yellow', 4),
        ('rr_second_swing_line', "Swingin' in the Breeze Coin Line", 'yellow', 5),
        ('rr_tricky_triangles_line', 'Tricky Triangles Coin Line', 'yellow', 5),
        ('rr_beneath_pole_goomba', 'Goomba', 'yellow', 1),
        ('rr_maze_coin_rings', 'Two coin rings at the spinning platforms', 'yellow', 16),
        ('rr_maze_lakitu', 'Lakitu in the Maze', 'yellow', 5),
        ('rr_maze_bob_ombs', 'Two Bob-ombs', 'yellow', 2),
        ('rr_maze_blue_coin', 'First Blue Coin from the Maze block', 'blue', 1),
        ('rr_maze_wall_kick_blue_coins', 'Remaining Maze Blue Coins with Wall Kick', 'blue', 5),
        ('rr_carpets_lakitu', 'Lakitu in the Carpets region', 'yellow', 5),
        ('rr_second_carpet_platform_coin', "Coin on the second carpet's grey platform", 'yellow', 1),
        ('rr_second_carpet_air_coin', 'Coin in the air along the second carpet', 'yellow', 1),
        ('rr_house_donut_lift_line', 'Vertical coin line on the House-path Donut Lifts', 'yellow', 5),
        ('rr_house_floor_line', 'Coin line on the Big House floor', 'yellow', 5),
        ('rr_house_glass_platform_line', 'Coin line on the second glass platform', 'yellow', 5),
        ('rr_house_return_line', 'Airborne coin line before returning to the House', 'yellow', 5),
        ('rr_cruiser_bob_ombs', 'Two Cruiser Bob-ombs', 'yellow', 2),
        ('rr_ship_pole_ring', 'Coin ring around the ship pole', 'yellow', 8),
        ('rr_somewhere_chuckya', 'Chuckya', 'yellow', 5),
    ),
    "The Princess's Secret Slide": (
        ('pss_single_yellow_coins', 'Single Yellow Coins', 'yellow', 20),
        ('pss_horizontal_coin_lines', 'Horizontal Coin Lines', 'yellow', 30),
        ('pss_blue_coin_block', 'Blue Coin Block with Ground Pound', 'blue', 6),
    ),
    'The Secret Aquarium': (
        ('sa_horizontal_coin_ring', 'Horizontal Coin Ring', 'yellow', 8),
        ('sa_vertical_coin_rings', 'Vertical Coin Rings', 'yellow', 32),
    ),
    'Wing Mario Over the Rainbow': (
        ('wmotr_rainbow_coin_rings', 'Four vertical coin rings around the rainbows', 'yellow', 32),
        ('wmotr_cloud_coin_ring', 'Horizontal coin ring below the pole cloud', 'yellow', 8),
    ),
    'Tower of the Wing Cap': (
        ('totwc_single_yellow_coins', 'Single Yellow Coins', 'yellow', 15),
    ),
    'Vanish Cap Under the Moat': (
        ('vcutm_bottom_slide_line', 'Coin line at the bottom of the slide', 'yellow', 5),
        ('vcutm_turning_lifts_block', '3-Coin Block before the turning lifts', 'yellow', 3),
        ('vcutm_end_marker_coins', 'Coins by the final star marker', 'yellow', 3),
    ),
    'Cavern of the Metal Cap': (
        ('cotmc_underwater_slope_line', 'Coin line under the water after the first Metal Cap Block', 'yellow', 5),
        ('cotmc_rock_bridge_line', 'Coin line after the rock bridge', 'yellow', 5),
        ('cotmc_snufits', 'Four Snufits', 'yellow', 8),
        ('cotmc_underwater_ring', 'Coin ring around the underwater star marker', 'yellow', 8),
        ('cotmc_stream_bottom_line', 'Coin line on the stream bottom', 'yellow', 5),
    ),
    'Bowser in the Dark World': (
        ('bitdw_coin_rings', 'Three rings of eight coins', 'yellow', 24),
        ('bitdw_coin_lines', 'Two lines of five coins', 'yellow', 10),
        ('bitdw_single_coins_before_slope', 'Single Yellow Coins before the slope', 'yellow', 18),
        ('bitdw_three_coin_block', '3-Coin Block', 'yellow', 3),
        ('bitdw_goombas', 'Six Goombas', 'yellow', 6),
        ('bitdw_slope_single_coins', 'Three coins on the slope', 'yellow', 3),
    ),
    'Bowser in the Fire Sea': (
        ('bitfs_start_single_coins', 'Coins on the first lava platforms', 'yellow', 2),
        ('bitfs_second_sinking_platform_line', 'Coin line on the second sinking platform', 'yellow', 5),
        ('bitfs_first_ring', 'Coin ring by the first Bully', 'yellow', 8),
        ('bitfs_first_bully', 'First Bully', 'yellow', 1),
        ('bitfs_start_goombas', 'Three Goombas', 'yellow', 3),
        ('bitfs_three_coin_block', '3-Coin Block', 'yellow', 3),
        ('bitfs_elevator_line', 'Coin line after the elevator', 'yellow', 5),
        ('bitfs_wire_grid_ring', 'Coin ring beneath the wire grid', 'yellow', 8),
        ('bitfs_vertical_drop_line', 'Vertical coin line after the second block', 'yellow', 5),
        ('bitfs_bob_omb_slope_line', 'Sloped coin line before the Bob-omb', 'yellow', 5),
        ('bitfs_ten_coin_block', '10-Coin Block by the Bob-omb', 'yellow', 10),
        ('bitfs_third_sinking_platform_line', 'Coin line on the third sinking platform', 'yellow', 5),
        ('bitfs_bob_omb', 'Bob-omb', 'yellow', 1),
        ('bitfs_upper_bullies', 'Three upper Bullies', 'yellow', 3),
    ),
    'Bowser in the Sky': (
        ('bits_tilting_w_coins', 'Coins on the tilting W platform', 'yellow', 3),
        ('bits_start_goombas', 'Two Goombas', 'yellow', 2),
        ('bits_start_fire_piranha', 'Initial Fire Piranha Plant', 'yellow', 1),
        ('bits_whomp_platform_lines', 'Two coin lines beneath the Whomp', 'yellow', 10),
        ('bits_whomp_jump_coins', 'Whomp coins available without Ground Pound', 'yellow', 5),
        ('bits_whomp_ground_pound_coins', 'Additional Whomp coins with Ground Pound', 'yellow', 5),
        ('bits_chuckya_enemy', 'Chuckya', 'yellow', 5),
        ('bits_chuckya_goomba', 'Goomba', 'yellow', 1),
        ('bits_raised_steps_coins', 'Coins on the raised steps', 'yellow', 6),
        ('bits_suction_platform_line', 'Coin line on the suction-cup platform', 'yellow', 5),
        ('bits_spinning_platform_coins', 'Coins on the spinning platform after the fifth Red Coin', 'yellow', 3),
        ('bits_arrow_ride_bob_ombs', 'Two Arrow Ride Bob-ombs', 'yellow', 2),
        ('bits_arrow_ride_fire_piranha', 'Arrow Ride Fire Piranha Plant', 'yellow', 1),
        ('bits_top_goombas', 'Four top Goombas', 'yellow', 4),
        ('bits_top_bob_ombs', 'Two top Bob-ombs', 'yellow', 2),
        ('bits_final_rotating_platform_line', 'Coin line before the final rotating platforms', 'yellow', 5),
    ),
    'Castle': (
        ('castle_grounds_bridge_coins', 'Coins under the bridge', 'yellow', 2),
        ('castle_lobby_coins', 'Coins in the lobby', 'yellow', 4),
        ('castle_courtyard_boos', 'Boos in the courtyard', 'yellow', 9),
    ),
}
