from typing import NamedTuple

from BaseClasses import ItemClassification, MultiWorld

from .Items import SM64Item
from .Locations import SM64Location


class SignData(NamedTuple):
    key: str
    area: str
    level: int
    dialog: int
    region: str
    rule: str = ""

    @property
    def location_name(self) -> str:
        return f"Sign Hint - {self.area} - {self.key}"


level_ids = {
    "Big Boo's Haunt": 4,
    "Cool, Cool Mountain": 5,
    "Castle Interior": 6,
    "Hazy Maze Cave": 7,
    "Shifting Sand Land": 8,
    "Bob-omb Battlefield": 9,
    "Snowman's Land": 10,
    "Wet-Dry World": 11,
    "Jolly Roger Bay": 12,
    "Tiny-Huge Island": 13,
    "Tick Tock Clock": 14,
    "Rainbow Ride": 15,
    "Castle Grounds": 16,
    "Bowser in the Dark World": 17,
    "Vanish Cap under the Moat": 18,
    "Bowser in the Fire Sea": 19,
    "Secret Aquarium": 20,
    "Bowser in the Sky": 21,
    "Lethal Lava Land": 22,
    "Dire, Dire Docks": 23,
    "Whomp's Fortress": 24,
    "Castle Courtyard": 26,
    "The Princess's Secret Slide": 27,
    "Cavern of the Metal Cap": 28,
    "Tower of the Wing Cap": 29,
    "Wing Mario over the Rainbow": 31,
    "Tall, Tall Mountain": 36,
}


def _sign(area: str, dialog: int, region: str, rule: str = "") -> SignData:
    key = f"dialog_{dialog:03d}"
    normalized_area = area.lower().replace(" ", "_").replace(",", "").replace("-", "_").replace("'", "")
    return SignData(f"{normalized_area}:{key}", area, level_ids[area], dialog, region, rule)


sign_data = (
    _sign("Castle Grounds", 50, "Menu"),
    _sign("Castle Grounds", 65, "Menu"),
    _sign("Castle Grounds", 167, "Menu"),
    _sign("Castle Grounds", 51, "Menu"),
    _sign("Castle Courtyard", 158, "Menu"),
    _sign("Castle Courtyard", 159, "Menu"),
    _sign("Castle Courtyard", 102, "Menu"),
    _sign("Castle Courtyard", 160, "Menu"),
    _sign("Castle Interior", 75, "Menu"),
    _sign("Castle Interior", 46, "Menu"),
    _sign("Castle Interior", 70, "Menu"),
    _sign("Castle Interior", 69, "Menu"),
    _sign("Castle Interior", 147, "Menu"),
    _sign("Castle Interior", 52, "Menu"),
    _sign("Castle Interior", 19, "Second Floor"),
    _sign("Castle Interior", 77, "Basement"),
    _sign("Bob-omb Battlefield", 15, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 8, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 95, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 113, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 64, "Bob-omb Battlefield - Island"),
    _sign("Bob-omb Battlefield", 35, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 74, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 104, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 50, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 53, "Bob-omb Battlefield - Island"),
    _sign("Bob-omb Battlefield", 39, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 112, "Bob-omb Battlefield"),
    _sign("Bob-omb Battlefield", 32, "Bob-omb Battlefield"),
    _sign("Whomp's Fortress", 18, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 36, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 42, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 51, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 96, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 78, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 104, "Whomp's Fortress"),
    _sign("Whomp's Fortress", 113, "Whomp's Fortress"),
    _sign("Jolly Roger Bay", 60, "Jolly Roger Bay"),
    _sign("Jolly Roger Bay", 73, "Jolly Roger Bay"),
    _sign("Jolly Roger Bay", 51, "Jolly Roger Bay"),
    _sign("Jolly Roger Bay", 113, "Jolly Roger Bay"),
    _sign("Jolly Roger Bay", 169, "Jolly Roger Bay"),
    _sign("Cool, Cool Mountain", 40, "Cool, Cool Mountain"),
    _sign("Cool, Cool Mountain", 87, "Cool, Cool Mountain"),
    _sign("Cool, Cool Mountain", 94, "Cool, Cool Mountain",
          "CANN | logic_ccm_wall_kicks_will_work_spin_jump"),
    _sign("Cool, Cool Mountain", 91, "Cool, Cool Mountain"),
    _sign("Cool, Cool Mountain", 49, "Cool, Cool Mountain",
          "CANN & TJ/LJ/BF/SF | logic_ccm_wall_kicks_will_work_spin_jump"),
    _sign("Cool, Cool Mountain", 170, "Cool, Cool Mountain"),
    _sign("Cool, Cool Mountain", 54, "Cool, Cool Mountain"),
    _sign("Big Boo's Haunt", 63, "Big Boo's Haunt"),
    _sign("Big Boo's Haunt", 85, "Big Boo's Haunt"),
    _sign("Big Boo's Haunt", 102, "Big Boo's Haunt"),
    _sign("Big Boo's Haunt", 86, "Big Boo's Haunt"),
    _sign("Hazy Maze Cave", 89, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 50, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 71, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 62, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 122, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 126, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 138, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 127, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 88, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 125, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 124, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 140, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 139, "Hazy Maze Cave"),
    _sign("Hazy Maze Cave", 43, "Hazy Maze Cave", "WK/LG/BF/SF/TJ"),
    _sign("Lethal Lava Land", 68, "Lethal Lava Land"),
    _sign("Lethal Lava Land", 16, "Lethal Lava Land"),
    _sign("Lethal Lava Land", 86, "Lethal Lava Land"),
    _sign("Shifting Sand Land", 16, "Shifting Sand Land - Stone Structure"),
    _sign("Shifting Sand Land", 32, "Shifting Sand Land"),
    _sign("Shifting Sand Land", 157, "Shifting Sand Land"),
    _sign("Shifting Sand Land", 43, "Shifting Sand Land"),
    _sign("Shifting Sand Land", 103, "Shifting Sand Land"),
    _sign("Dire, Dire Docks", 53, "Dire, Dire Docks"),
    _sign("Snowman's Land", 86, "Snowman's Land"),
    _sign("Snowman's Land", 61, "Snowman's Land"),
    _sign("Snowman's Land", 148, "Snowman's Land"),
    _sign("Snowman's Land", 16, "Snowman's Land - Whirl from the Freezing Pond"),
    _sign("Wet-Dry World", 81, "Wet-Dry World"),
    _sign("Wet-Dry World", 53, "Wet-Dry World - Top"),
    _sign("Tall, Tall Mountain", 94, "Tall, Tall Mountain"),
    _sign("Tall, Tall Mountain", 91, "Tall, Tall Mountain"),
    _sign("Tall, Tall Mountain", 72, "Tall, Tall Mountain - Middle"),
    _sign("Tiny-Huge Island", 91, "Tiny-Huge Island - Windswept Valley"),
    _sign("Tiny-Huge Island", 166, "Tiny-Huge Island - Koopa the Quick"),
    _sign("Tiny-Huge Island", 165, "Tiny-Huge Island (Huge)",
          "CANN | {Tiny-Huge Island - Koopa the Quick} & LJ"),
    _sign("The Princess's Secret Slide", 149, "The Princess's Secret Slide"),
    _sign("Cavern of the Metal Cap", 123, "Cavern of the Metal Cap"),
    _sign("Bowser in the Dark World", 66, "Bowser in the Dark World",
          "PURPLE_SWITCHES | logic_bitdw_purple_switch_bypass"),
)


sign_data_by_location_name = {sign.location_name: sign for sign in sign_data}


joke_hints = (
    "The real hint was the coins collected along the way.",
    "Thank you Mario! But our hint is in another castle.",
    "The sign knows, but it is not telling.",
    "Try looking somewhere that contains an item.",
    "A Power Star would be useful here. Too bad there are none.",
    "This sign has been advised by its lawyer not to comment.",
    "Bowser recommends checking every location twice.",
    "This sign was shuffled without its useful information.",
    "The princess is probably in a different multiworld.",
    "Long Jump remains longer than Short Jump.",
    "Coins are round so they cannot point toward progression.",
    "Have you tried reading a different sign?",
    "The next sign is rumored to know more.",
    "The previous sign definitely knew more.",
    "A Toad wrote this hint and immediately forgot it.",
    "MIPS declined to clip the answer through the door.",
    "The cannon is loaded with unhelpful advice.",
    "This hint requires a movement ability that does not exist.",
    "Ground Pound the sign for absolutely no additional information.",
    "The item is somewhere between the Menu and victory.",
    "Consult the nearest suspicious mushroom.",
    "A Koopa Troopa took the useful hint up the mountain.",
    "The water level is too low to read the fine print.",
    "The water level is too high to read the fine print.",
    "The clock is stopped, but this hint is still wasting time.",
    "The clock is moving, but this hint is going nowhere.",
    "Carpets are excellent transportation and terrible informants.",
    "The treasure chest contained another treasure chest.",
    "The Purple Switch has switched to saying nothing.",
    "The Rolling Log has rolled away with the answer.",
    "The Warp Pipe leads directly to another Warp Pipe.",
    "The swimming beast saw the item but cannot describe it.",
    "The penguin knows where it is and is keeping it for the baby.",
    "The elevator is currently carrying the useful hint upstairs.",
    "The staircase spawned, but the information did not.",
    "Hoot is asleep and unavailable for hint duty.",
    "The sunken ship took this hint down with it.",
    "Unagi ate the part of the sign that mattered.",
    "The Whomp King flattened the useful sentence.",
    "King Bob-omb considers this information classified.",
    "Ukiki has the hint. Ukiki also has no intention of returning it.",
    "Klepto stole the answer before the sign loaded.",
    "The Manta Ray left only rings, not directions.",
    "The Merry-go-round keeps returning to this same useless hint.",
    "The maze exit is closed for hint maintenance.",
    "The toxic cloud obscures all relevant details.",
    "The metal cap makes this hint heavier, not better.",
    "The vanish cap made the useful words on this sign disappear.",
    "The wing cap carried the answer beyond the drawing distance.",
    "The Fly Guy flew away before answering.",
    "The Chuckya threw the hint into another region.",
    "The Goomba knew one thing and then got stepped on.",
    "The Boo is invisible, much like the useful information here.",
    "The Big Boo has a big secret and a small attention span.",
    "The Thwomp refuses to discuss anything until stomped.",
    "The Snufit fired the answer into the void.",
    "The Scuttlebug scuttled off with the important part.",
    "The Mr. I saw everything and explained nothing.",
    "The Spindrift suggests spinning until an item appears.",
    "The Mr. Blizzard forecast calls for scattered filler.",
    "The Piranha Plant says progression tastes better than filler.",
    "The Amp finds this hint positively useless.",
    "The Lakitu camera was pointed away from the item.",
    "The Swoop only comes out when nobody needs directions.",
    "The Monty Mole buried the useful hint.",
    "The Bully pushed the answer into lava.",
    "The Heave Ho threw the answer onto a higher platform.",
    "The Bob-omb exploded before finishing the sentence.",
    "The Koopa Shell is fast enough to outrun useful advice.",
    "The Crazy Box contains several bad decisions.",
    "The Blue Coin Block is blue. This has been confirmed.",
    "The Red Coin is red. Further research is ongoing.",
    "Ten coins are worth exactly ten coins.",
    "Three coins are worth less than ten coins.",
    "One coin is the smallest nonzero number of coins.",
    "The 1-Up would be more useful if lives still existed.",
    "The butterfly refuses to become useful on command.",
    "The Bowser Arena Bomb strongly recommends throwing it at Bowser.",
    "The key opens a door. Which door remains an exercise for Mario.",
    "The basement is generally located below the first floor.",
    "The second floor is generally located above the first floor.",
    "The third floor continues the established vertical pattern.",
    "The roof is outside, despite being on top of the castle.",
    "The moat contains water unless circumstances suggest otherwise.",
    "The cannon shoots Mario in the direction it is pointing.",
    "The sign has achieved full accessibility to no useful facts.",
    "There are ninety-one signs and this one drew the short straw.",
    "Someone's location contains your item. We hope this helps.",
    "An important item is in a world you can probably access eventually.",
    "Progression has been detected somewhere in the multiworld.",
    "Your item is in another player's problem.",
    "Another player has your progression. They have been notified emotionally.",
    "Consider checking locations you have not checked.",
    "Checked locations are less likely to contain unchecked items.",
    "Your progression has been placed in a safe location. Unfortunately, Mario is not there.",
    "The randomizer accepts no responsibility for where it put your stuff.",
    "Somebody else's item is exactly where your item should have been.",
    "Please allow three to five business spheres for progression.",
    "Your next progression item is pending shipment from another world.",
    "The seed knows what you need and has chosen violence.",
    "Lakitu has footage of the item but refuses to leave camera mode.",
    "Yoshi has been on the roof this entire time and has contributed nothing.",
    "Toad has information, but first you must stare directly into his soul.",
    "Bowser knows where Peach is. This has somehow not shortened the game.",
    "Peach baked a cake. Its location has not been randomized.",
    "The castle has many doors. Most of them are currently somebody else's problem.",
    "The endless stairs are only endless when they feel like it.",
    "The mirror reflects everything except useful information.",
    "The basement rabbit requests that Mario stop exploiting collision.",
    "MIPS knows exactly what you're planning and wants no part of it.",
    "Parallel universes are outside the current logic rules.",
    "Half an A press is still more useful than this sign.",
    "Please build up sufficient speed before attempting to read the next hint.",
    "Something strange happens when you read this sign with negative speed.",
    "The camera recommends fighting it instead of the level.",
    "Wall kicks will work, allegedly.",
    "The slope has reviewed Mario's angle and rejected his application.",
    "Fall damage is temporary. Progression is forever.",
    "The quicksand is approximately as helpful as this sign.",
    "Do not punch the treasure chest. It knows what you did.",
    "The piano knows where the item is. Do not ask the piano.",
    "The eel is not coming out to discuss randomizer logic.",
    "The monkey has reviewed the terms of the item-link agreement.",
    "The owl can carry Mario, but not this conversation.",
    "There are two baby penguins. Choose your crimes carefully.",
    "Press A to perform an action associated with the A Button.",
    "Running is faster than standing still.",
    "Jumping allows Mario to temporarily stop touching the ground.",
    "Doors commonly lead to the other side of doors.",
    "Water is easier to swim in than most walls.",
    "Lava should be avoided except when avoiding it is inconvenient.",
    "Falling downward is significantly easier than falling upward.",
    "A wall prevents movement until it doesn't.",
    "Enemies are generally hostile unless dead.",
    "Eight Red Coins is exactly enough Red Coins to collect eight Red Coins.",
    "Collecting the eighth Red Coin is difficult before collecting seven others.",
    "Blue Coins are worth more coins because they are more blue.",
    "Yellow Coins are the standard unit of coin.",
    "An unopened door may be opened if Mario is capable of opening it.",
    "A locked door is similar to an unlocked door with additional requirements.",
    "The castle has an inside and an outside.",
    "The courtyard is outside but still somehow part of the castle.",
    "Up is the preferred direction for reaching higher platforms.",
    "Moving Mario toward the objective may reduce the distance to the objective.",
    "There are no warp pipes in Bowser in the Fire Sea, despite what some devs might think."
)


tip_hints = (
    "Gray coins heal Mario but do not add another coin.",
    "Secret courses, cap stages, and Bowser stages use Castle movement items.",
    "Coinsanity places checks at evenly spaced coin totals below the Coins Star requirement.",
    "Three-Coin and Ten-Coin Blocks require their unlocks even without Blocksanity.",
    "With 1-Up checks disabled, 1-Up Mushrooms heal Mario to full health.",
    "Easy Butterflies makes a butterfly become a 1-Up regardless of Mario's distance.",
    "A Cannon Unlock is still required after its Bob-omb Buddy check is sent.",
    "Drain the Moat is a check; Vanish Cap Under the Moat uses its unlock item.",
    "No Despawns preserves timed coins and 1-Ups and grants ones lost to hazards.",
    "Save files are a thing of the past. It's all on the Archipelago server now!",
    "If you aren't using Universal Tracker, you should cease not using it immediately.",
    "Please include your Universal Tracker /explain details with any questions or reports regarding logic.",
    "If your game was generated with a 0.2.X apworld, set the branch to 0.2.0 when you build sm64ex"
)


fallback_hints = (*joke_hints, *tip_hints)


def create_sign_locations(multiworld: MultiWorld, player: int) -> None:
    for sign in sign_data:
        region = multiworld.get_region(sign.region, player)
        location = SM64Location(player, sign.location_name, None, region)
        location.place_locked_item(SM64Item("Sign Hint Event", ItemClassification.filler, None, player))
        region.locations.append(location)
